numero1=float(input("Primer Numero: "))
numero2=float(input("Segundo Numero: "))
print("Suma")
print(numero1,"+",numero2, numero1+numero2)
print("Resta")
print(numero1,"-",numero2, numero1-numero2)
print("Multiplicacion")
print(numero1,"*",numero2, numero1*numero2)
print("Division")
print(numero1,"/",numero2, numero1/numero2)
print("Modulo")
print(numero1,"%",numero2, numero1%numero2)
print("Exponete")
print(numero1,"**",numero2, numero1**numero2)