palabras_aprendidas = float(input("Palabras aprendidas hoy: "))
palabras_repasadas = float(input("Palabras repasadas hoy: "))

print("Total de practica")
print(palabras_aprendidas, "+", palabras_repasadas, palabras_aprendidas + palabras_repasadas)
print("Diferencia")
print(palabras_aprendidas, "-", palabras_repasadas, palabras_aprendidas - palabras_repasadas)
print("Practica semanal estimada")
print(palabras_aprendidas, "*", 7, palabras_aprendidas * 7)
print("Promedio entre dos actividades")
print(palabras_aprendidas + palabras_repasadas, "/", 2, (palabras_aprendidas + palabras_repasadas) / 2)
print("Restante al dividir en grupos de 5")
print(palabras_aprendidas, "%", 5, palabras_aprendidas % 5)
print("Reto elevado")
print(palabras_aprendidas, "**", 2, palabras_aprendidas ** 2)
